name: Nightly

on:
  push:
    branches: [ "main" ]


jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install libarchive
      run: sudo apt update && sudo apt install libarchive-dev
    - name: Install zig
      run: wget https://ziglang.org/download/0.14.0/zig-linux-x86_64-0.14.0.tar.xz && tar -xvf zig-linux-x86_64-0.14.0.tar.xz
    - name: Compile
      run: ./zig-linux-x86_64-0.14.0/zig build -Doptimize=ReleaseFast -Dcpu=baseline
    - name: Compute Short SHA
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly-${{ github.sha }}
        name: Nightly Build ${{ steps.vars.outputs.sha_short }}
        files: |
          ./zig-out/bin/zigdemu
          ./zig-out/bin/zigd
